### ISSUE TITLE
Browser won't launch on Mac OS

### ISSUE THREAD

**Issue by kennedy0** [cmontesano/xappt_qt#22]
On first launch, both `xappt_qt.config.start_minimized` and `xappt_qt.config.minimize_to_tray` are True (not sure why?), so `browser.show()` is never allowed to run.

https://github.com/cmontesano/xappt_qt/blob/f42cb0f631238d5b2e065052db875172c11ec77c/xappt_qt/browser.py#L142-L148

Should this line:
https://github.com/cmontesano/xappt_qt/blob/f42cb0f631238d5b2e065052db875172c11ec77c/xappt_qt/browser.py#L146
be outdented once to resolve the issue?

**Comment by cmontesano** [comment]
Interesting - outdenting that line would show the browser when `minimize_to_tray` is `True`. But we don't want since we want it in the tray - which is to say that we want it hidden. On MacOS `minimize_to_tray` should always be `False`, so I'll look in to why that's not the case.

**Comment by cmontesano** [comment]
https://github.com/cmontesano/xappt_qt/blob/f42cb0f631238d5b2e065052db875172c11ec77c/xappt_qt/browser.py#L23

So this is set at the head of the file:

https://github.com/cmontesano/xappt_qt/blob/f42cb0f631238d5b2e065052db875172c11ec77c/xappt_qt/browser.py#L73-L76

And this should force `minimize_to_tray` to `False` if the platform is `Darwin`.

So something might be changing this after the fact. I don't have a mac to test it, but I can modify `DISABLE_TRAY_ICON` to be always `True` and hopefully track down the issue.

**Comment by kennedy0** [comment]
Thanks, that's a good lead to follow that I had missed. I can do some digging on my end tomorrow morning.

**Comment by cmontesano** [comment]
I confirmed that `minimize_to_tray` is being set to `True` at some point even when `DISABLE_TRAY_ICON` is set. Now I just have to find out where and why.

**Comment by cmontesano** [comment]
https://github.com/cmontesano/xappt_qt/blob/f42cb0f631238d5b2e065052db875172c11ec77c/xappt_qt/browser.py#L57-L60

Found it.

**Comment by cmontesano** [comment]
So I tried setting `default` to `not DISABLE_TRAY_ICON`, but that doesn't help if it's already saved to the config file. So I'm working on a way to ensure that it's always `False` even if it's in the config file.

**Comment by cmontesano** [comment]
I have a fix that I will push shortly.
